from __future__ import annotations

WEBSITE_CHECK_FIELD_LABELS: dict[str, str] = {
    "scan_id": "Scan ID",
    "original_url": "Original URL",
    "target_url": "Target URL",
    "final_url": "Final URL",
    "normalized_url": "Normalized URL",
    "domain": "Domain",
    "hostname": "Hostname",
    "is_available": "Availability",
    "reachable": "Reachable",
    "http_status_code": "HTTP Status Code",
    "response_time_ms": "Response Time (ms)",
    "https_enabled": "HTTPS Enabled",
    "ssl_valid": "SSL Valid",
    "ssl_issuer": "SSL Issuer",
    "ssl_subject": "SSL Subject",
    "ssl_expiry_date": "SSL Expiry Date",
    "security_score": "Security Score",
    "risk_level": "Risk Level",
    "grade": "Grade",
    "security_headers": "Security Headers",
    "missing_headers": "Missing Headers",
    "present_headers": "Present Headers",
    "has_hsts": "HSTS Enabled",
    "has_csp": "CSP Enabled",
    "has_x_frame_options": "X-Frame-Options Enabled",
    "has_x_content_type_options": "X-Content-Type-Options Enabled",
    "dns_records": "DNS Records",
    "spf_found": "SPF Found",
    "dmarc_found": "DMARC Found",
    "dkim_guidance": "DKIM Guidance",
    "technologies": "Technologies",
    "raw_headers": "Raw Headers",
    "created_at": "Created At",
    "updated_at": "Updated At",
}
