from __future__ import annotations

from enum import Enum
from typing import Any, ClassVar

from pydantic import BaseModel, ConfigDict, Field, field_validator

from app.utils.validators import validate_website_url


class WebsiteScanProfile(str, Enum):
    """
    Supported website scan profiles.

    The MVP starts with a safe basic profile only.
    More profiles can be added later, such as:
    - standard
    - advanced_authorized
    """

    BASIC = "basic"


class WebsiteScanStatus(str, Enum):
    """
    Website scan response status.
    """

    COMPLETED = "completed"
    FAILED = "failed"


class WebsiteFindingSeverity(str, Enum):
    """
    Severity levels returned in website scan responses.
    """

    CRITICAL = "critical"
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"
    INFO = "info"


class WebsiteRiskLevel(str, Enum):
    """
    Business-friendly website risk levels returned by the risk engine.
    """

    MINIMAL = "minimal"
    LOW = "low"
    MODERATE = "moderate"
    HIGH = "high"
    CRITICAL = "critical"


class WebsiteScanRequest(BaseModel):
    """
    Request body for starting a safe website security scan.

    The backend only accepts the scan when the user confirms that they own
    the target or have explicit authorization to scan it.
    """

    model_config: ClassVar[ConfigDict] = ConfigDict(
        extra="forbid",
        str_strip_whitespace=True,
        json_schema_extra={
            "example": {
                "target_url": "https://example.com",
                "scan_profile": "basic",
                "authorization_confirmed": True,
            }
        },
    )

    target_url: str = Field(
        ...,
        min_length=8,
        max_length=500,
        description=(
            "Authorized website URL to scan. "
            "The URL must start with http:// or https://."
        ),
    )

    scan_profile: WebsiteScanProfile = Field(
        default=WebsiteScanProfile.BASIC,
        description="Website scan profile. The MVP supports only basic safe checks.",
    )

    authorization_confirmed: bool = Field(
        ...,
        description=(
            "Must be true only if the user owns the target "
            "or has explicit permission to scan it."
        ),
    )

    @field_validator("target_url")
    @classmethod
    def validate_target_url(cls, value: str) -> str:
        """
        Validate and normalize the website URL before scanning.
        """

        return validate_website_url(value)


class WebsiteFindingPreview(BaseModel):
    """
    Lightweight finding object returned after a website scan.

    Full finding details can later be stored in the database and displayed
    in the findings page or generated report.
    """

    model_config: ClassVar[ConfigDict] = ConfigDict(extra="forbid")

    title: str = Field(
        ...,
        min_length=3,
        max_length=255,
        description="Short finding title.",
    )

    severity: WebsiteFindingSeverity = Field(
        ...,
        description="Finding severity level.",
    )

    category: str = Field(
        ...,
        min_length=2,
        max_length=100,
        description="Finding category, such as security_headers or ssl_tls.",
    )

    description: str = Field(
        ...,
        min_length=5,
        description="Technical explanation of the finding.",
    )

    recommendation: str = Field(
        ...,
        min_length=5,
        description="Recommended remediation step.",
    )


class WebsiteRiskDeduction(BaseModel):
    """
    Explainable scoring deduction generated by the CyberShield360 risk engine.
    """

    model_config: ClassVar[ConfigDict] = ConfigDict(extra="forbid")

    rule_id: str = Field(
        ...,
        min_length=3,
        max_length=100,
        description="Stable rule identifier used by the risk engine.",
    )

    title: str = Field(
        ...,
        min_length=3,
        max_length=255,
        description="Risk rule title.",
    )

    category: str = Field(
        ...,
        min_length=2,
        max_length=100,
        description="Risk category.",
    )

    severity: WebsiteFindingSeverity = Field(
        ...,
        description="Risk severity.",
    )

    deduction: int = Field(
        ...,
        ge=0,
        le=100,
        description="Score deduction applied by this rule.",
    )

    evidence: str = Field(
        ...,
        min_length=3,
        description="Evidence that triggered the deduction.",
    )

    business_impact: str = Field(
        ...,
        min_length=3,
        description="Business impact of the detected issue.",
    )

    recommendation: str = Field(
        ...,
        min_length=3,
        description="Recommended remediation action.",
    )

    detection_method: str = Field(
        ...,
        min_length=3,
        description="How the issue was detected.",
    )

    confidence: str = Field(
        default="high",
        min_length=2,
        max_length=50,
        description="Confidence level of the detection.",
    )

    mappings: dict[str, list[str]] = Field(
        default_factory=dict,
        description="Framework mappings such as OWASP Top 10 and NIST CSF.",
    )


class WebsitePositiveSecuritySignal(BaseModel):
    """
    Positive security signal detected during assessment.
    """

    model_config: ClassVar[ConfigDict] = ConfigDict(extra="forbid")

    title: str = Field(
        ...,
        min_length=3,
        max_length=255,
        description="Positive security signal title.",
    )

    category: str = Field(
        ...,
        min_length=2,
        max_length=100,
        description="Positive signal category.",
    )

    evidence: str = Field(
        ...,
        min_length=3,
        description="Evidence supporting the positive signal.",
    )

    mappings: dict[str, list[str]] = Field(
        default_factory=dict,
        description="Framework mappings such as OWASP Top 10 and NIST CSF.",
    )


class WebsiteRiskAssessment(BaseModel):
    """
    Professional risk assessment returned by the CyberShield360 risk engine.
    """

    model_config: ClassVar[ConfigDict] = ConfigDict(extra="forbid")

    target: str | None = Field(
        default=None,
        description="Assessed website target.",
    )

    security_score: int = Field(
        ...,
        ge=0,
        le=100,
        description="Calculated website security score from 0 to 100.",
    )

    risk_level: WebsiteRiskLevel = Field(
        ...,
        description="Business-friendly risk level.",
    )

    grade: str = Field(
        ...,
        min_length=1,
        max_length=20,
        description="Letter grade derived from the security score.",
    )

    executive_summary: str = Field(
        ...,
        min_length=3,
        description="Executive-level summary suitable for reports and dashboards.",
    )

    detection_summary: str = Field(
        ...,
        min_length=3,
        description="Summary of what the automated checks evaluated.",
    )

    key_risk_drivers: list[str] = Field(
        default_factory=list,
        description="Top risks that most affected the score.",
    )

    priority_actions: list[str] = Field(
        default_factory=list,
        description="Prioritized remediation actions.",
    )

    positive_security_signals: list[WebsitePositiveSecuritySignal] = Field(
        default_factory=list,
        description="Positive security signals detected during the scan.",
    )

    severity_counts: dict[str, int] = Field(
        default_factory=dict,
        description="Count of deductions by severity.",
    )

    category_counts: dict[str, int] = Field(
        default_factory=dict,
        description="Count of deductions by category.",
    )

    scoring_deductions: list[WebsiteRiskDeduction] = Field(
        default_factory=list,
        description="Explainable score deductions.",
    )

    total_deduction: int = Field(
        ...,
        ge=0,
        le=100,
        description="Total capped deduction applied to the base score.",
    )

    assessment_coverage: dict[str, bool] = Field(
        default_factory=dict,
        description="Shows which evidence areas were available for scoring.",
    )

    scoring_version: str = Field(
        ...,
        min_length=1,
        max_length=50,
        description="Risk scoring engine version.",
    )

    generated_at: str = Field(
        ...,
        description="Risk assessment generation timestamp.",
    )


class WebsiteScanResult(BaseModel):
    """
    Structured website scan result returned by the scanner service.

    This object contains safe, non-invasive evidence collected from:
    - HTTP availability check
    - HTTPS status
    - SSL/TLS certificate check
    - Security headers check
    - DNS/email security checks
    - Basic technology detection from headers
    - Explainable risk assessment
    """

    model_config: ClassVar[ConfigDict] = ConfigDict(extra="forbid")

    original_url: str = Field(
        ...,
        description="Original URL submitted by the user.",
    )

    final_url: str | None = Field(
        default=None,
        description="Final URL after redirects, if applicable.",
    )

    domain: str = Field(
        ...,
        description="Extracted domain name from the website URL.",
    )

    is_available: bool = Field(
        ...,
        description="True if the website responded to the availability check.",
    )

    http_status_code: int | None = Field(
        default=None,
        ge=100,
        le=599,
        description="HTTP status code returned by the website.",
    )

    response_time_ms: int | None = Field(
        default=None,
        ge=0,
        description="Website response time in milliseconds.",
    )

    https_enabled: bool = Field(
        ...,
        description="True if the website uses HTTPS.",
    )

    ssl_valid: bool | None = Field(
        default=None,
        description="True if the SSL/TLS certificate is valid.",
    )

    ssl_issuer: str | None = Field(
        default=None,
        max_length=255,
        description="SSL/TLS certificate issuer.",
    )

    ssl_subject: str | None = Field(
        default=None,
        max_length=255,
        description="SSL/TLS certificate subject.",
    )

    ssl_expiry_date: str | None = Field(
        default=None,
        description="SSL/TLS certificate expiry date in ISO format.",
    )

    security_headers: dict[str, bool | str | None] = Field(
        default_factory=dict,
        description="Detected and missing security headers.",
    )

    dns_records: dict[str, list[str]] = Field(
        default_factory=dict,
        description="DNS records such as A, AAAA, MX, NS, and TXT.",
    )

    spf_found: bool | None = Field(
        default=None,
        description="True if SPF record is found.",
    )

    dmarc_found: bool | None = Field(
        default=None,
        description="True if DMARC record is found.",
    )

    caa_found: bool | None = Field(
        default=None,
        description="True if CAA records are found for certificate issuance control.",
    )

    caa_records: list[str] = Field(
        default_factory=list,
        description="CAA DNS records controlling which certificate authorities may issue certificates.",
    )

    dkim_guidance: str | None = Field(
        default=None,
        description="DKIM guidance because selectors cannot always be detected safely.",
    )

    technologies_detected: dict[str, str | None] = Field(
        default_factory=dict,
        description="Basic technology hints detected from safe HTTP headers only.",
    )

    raw_headers: dict[str, str] = Field(
        default_factory=dict,
        description="Raw HTTP response headers collected during the safe check.",
    )

    risk_assessment: WebsiteRiskAssessment | None = Field(
        default=None,
        description="Explainable CyberShield360 risk assessment for the scan.",
    )

    metadata: dict[str, Any] = Field(
        default_factory=dict,
        description="Optional extensible metadata for future scanner enhancements.",
    )


class WebsiteScanResponse(BaseModel):
    """
    API response returned after a website scan completes.
    """

    model_config: ClassVar[ConfigDict] = ConfigDict(
        extra="forbid",
        json_schema_extra={
            "example": {
                "scan_id": 1,
                "status": "completed",
                "target_url": "https://example.com",
                "security_score": 82,
                "findings_count": 2,
                "findings": [
                    {
                        "title": "Missing Content-Security-Policy Header",
                        "severity": "medium",
                        "category": "security_headers",
                        "description": (
                            "The website does not define a "
                            "Content-Security-Policy header."
                        ),
                        "recommendation": (
                            "Add a strong Content-Security-Policy header."
                        ),
                    }
                ],
                "result": {
                    "original_url": "https://example.com",
                    "final_url": "https://example.com",
                    "domain": "example.com",
                    "is_available": True,
                    "http_status_code": 200,
                    "response_time_ms": 120,
                    "https_enabled": True,
                    "ssl_valid": True,
                    "ssl_issuer": "Example CA",
                    "ssl_subject": "example.com",
                    "ssl_expiry_date": "2026-12-31T00:00:00+00:00",
                    "security_headers": {},
                    "dns_records": {},
                    "spf_found": True,
                    "dmarc_found": True,
                    "dkim_guidance": "Review DKIM selectors with the mail provider.",
                    "technologies_detected": {},
                    "raw_headers": {},
                    "risk_assessment": {
                        "target": "https://example.com",
                        "security_score": 82,
                        "risk_level": "low",
                        "grade": "B+",
                        "executive_summary": "Example executive summary.",
                        "detection_summary": "Example detection summary.",
                        "key_risk_drivers": [],
                        "priority_actions": [],
                        "positive_security_signals": [],
                        "severity_counts": {},
                        "category_counts": {},
                        "scoring_deductions": [],
                        "total_deduction": 18,
                        "assessment_coverage": {},
                        "scoring_version": "1.0.0",
                        "generated_at": "2026-06-08T00:00:00+00:00",
                    },
                    "metadata": {},
                },
                "message": "Website scan completed successfully.",
            }
        },
    )

    scan_id: int = Field(
        ...,
        ge=1,
        description="Database ID of the completed scan.",
    )

    status: WebsiteScanStatus = Field(
        ...,
        description="Final scan status.",
    )

    target_url: str = Field(
        ...,
        description="Scanned website URL.",
    )

    security_score: int = Field(
        ...,
        ge=0,
        le=100,
        description="Calculated security score from 0 to 100.",
    )

    findings_count: int = Field(
        ...,
        ge=0,
        description="Total number of findings returned by the scan.",
    )

    findings: list[WebsiteFindingPreview] = Field(
        default_factory=list,
        description="List of lightweight findings returned to the frontend.",
    )

    result: WebsiteScanResult | None = Field(
        default=None,
        description="Structured website scan result.",
    )

    message: str = Field(
        ...,
        description="Human-readable response message.",
    )